In [4]:
print("hello")

hello


In [5]:
import numpy as np

In [6]:
a = input()

 1


In [5]:
a

'12'

In [6]:
b = int(input())

 4


In [7]:
b

4

In [9]:
n, m = map(int, input().split())

 12 4


In [10]:
n

12

In [11]:
m

4

In [17]:
x, y = map(int, input().split())

data = []
for _ in range (x):
    row = list(map(int, input().split()))
    data.append(row)
    
array = np.array(data)
print(array)

 2 2
 1 1 1
 1 1 1


[[1 1 1]
 [1 1 1]]


In [19]:
my_array = np.arange(30)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
np.shape(my_array)

(30,)

In [21]:
np.size(my_array)

30

In [22]:
np.ndim(my_array)

1

In [28]:
arr = my_array.reshape(3,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [32]:
a1 = np.array([[1, 2],
              [3, 4]])
a2 = np.array([[5, 6],
              [7, 8]])
a1

array([[1, 2],
       [3, 4]])

In [36]:
np.vstack((a1, a2)) #vertically stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.hstack((a1, a2)) #horizontally stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [7]:
e = np.arange(1, 25).reshape(2, 12)
e

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

axis=0 yukaridan asagi
axis=1 soldan saga

In [8]:
e.max()

24

In [9]:
e.min()

1

In [10]:
e.sum()

300

In [15]:
e[0:2, 3:5] #[satir, sutun]

array([[ 4,  5],
       [16, 17]])

In [16]:
rng = np.random.default_rng()  
rng.random(3) 

array([0.18170013, 0.09171011, 0.51188446])

In [17]:
rng.random(6)

array([0.23261201, 0.15974593, 0.74381514, 0.36572006, 0.35017272,
       0.04812174])

In [22]:
narr = rng.integers(12, size = (2,3))
narr

array([[8, 8, 3],
       [1, 9, 1]], dtype=int64)

In [23]:
np.unique(narr)

array([1, 3, 8, 9], dtype=int64)

 return_index=True dediğin için, bu benzersiz elemanlardan her biri dizide ilk nerede görülmüş, onun indekslerini döndürüyor.

In [25]:
unique_values, indices_list = np.unique(narr, return_index=True)
print(indices_list)

[3 2 0 4]


farkli valuelardan array icinde kacar tane oldugunu dondurur.

In [28]:
unique_values, occurrence_count = np.unique(narr, return_counts=True)
print(occurrence_count)

[2 1 2 1]


Bütün farklı satırları bulup, hangi sırada ilk kez karşılaştığını ve kaç kez tekrarlandığını söylüyor.
Yani np.unique(axis=0) burada satırları kontrol ediyor!
return_index=True → İlk nerede görüldü?
return_counts=True → Kaç kere geçti?

In [29]:
a_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [1, 2, 3, 4],   # Bak bu satır yukarıdaki ile aynı
    [9,10,11,12]
])

unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)

print("Unique Rows:\n", unique_rows)
print("Indices:", indices)
print("Occurrence Counts:", occurrence_count)

Unique Rows:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Indices: [0 1 3]
Occurrence Counts: [2 1 1]


In [31]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [35]:
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [39]:
help(e.flatten)

Help on built-in function flatten:

flatten(...) method of numpy.ndarray instance
    a.flatten(order='C')
    
    Return a copy of the array collapsed into one dimension.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.
    
    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.
    
    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.
    
    Examples
    --------
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3, 2, 4]

In [40]:
?min

Docstring:
min(iterable, *[, default=obj, key=func]) -> value
min(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its smallest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the smallest argument.
Type:      builtin_function_or_method

In [41]:
??sum

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

NumPy Doc 
https://numpy.org/devdocs/user/absolute_beginners.html

In [43]:
test = np.random.randint(1, 10, size = (3, 3))
test

array([[3, 8, 1],
       [6, 9, 4],
       [4, 7, 7]])

In [44]:
np.max(test)

9

In [45]:
np.min(test)

1

In [46]:
np.std(test)

2.454524670486058

In [47]:
np.mean(test)

5.444444444444445

In [48]:
new = np.random.randint(1, 26, size = (5, 5))

In [49]:
new

array([[ 5,  6, 10, 21,  3],
       [24, 20,  8, 13, 18],
       [25, 12, 11, 23, 23],
       [ 8,  8, 22, 20, 10],
       [17, 10, 14, 14,  7]])

In [50]:
np.max(new)

25

In [51]:
bmean = np.mean(new) > new

In [52]:
bmean

array([[ True,  True,  True, False,  True],
       [False, False,  True,  True, False],
       [False,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [False,  True,  True,  True,  True]])

In [53]:
new.sum(axis = 1)

array([45, 83, 94, 68, 62])

In [54]:
new.sum(axis = 0)

array([79, 56, 65, 91, 61])

In [56]:
new[new > np.mean(new)]

array([21, 24, 20, 18, 25, 23, 23, 22, 20, 17])

In [57]:
bigdata = np.random.randint(0, 100, size = 10000)
bigdata

array([ 1, 25, 32, ..., 67, 14, 87])

In [59]:
bigdata[bigdata > np.mean(bigdata)]

array([95, 90, 76, ..., 76, 67, 87])

In [61]:
bigdata.size

10000

In [62]:
bigdata[bigdata > np.mean(bigdata)].size

5013

In [63]:
np.std(bigdata[bigdata > np.mean(bigdata)])

14.378372040836526

In [65]:
norm = np.mean(bigdata) / np.std(bigdata)
norm

1.7083366590798916

In [66]:
zeros = np.random.randint(0, 5, size = (6, 6))
zeros

array([[2, 4, 0, 4, 2, 0],
       [1, 2, 4, 0, 1, 3],
       [1, 3, 3, 1, 1, 0],
       [2, 3, 0, 4, 2, 3],
       [1, 1, 2, 1, 3, 0],
       [3, 0, 2, 3, 4, 1]])

In [68]:
non_zero = zeros[zeros != 0]
non_zero

array([2, 4, 4, 2, 1, 2, 4, 1, 3, 1, 3, 3, 1, 1, 2, 3, 4, 2, 3, 1, 1, 2,
       1, 3, 3, 2, 3, 4, 1])

In [69]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

common = np.intersect1d(arr1, arr2)
common

array([4, 5])

In [70]:
?np.intersect1d

Signature: np.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
Docstring:
Find the intersection of two arrays.

Return the sorted, unique values that are in both of the input arrays.

Parameters
----------
ar1, ar2 : array_like
    Input arrays. Will be flattened if not already 1D.
assume_unique : bool
    If True, the input arrays are both assumed to be unique, which
    can speed up the calculation.  If True but ``ar1`` or ``ar2`` are not
    unique, incorrect results and out-of-bounds indices could result.
    Default is False.
return_indices : bool
    If True, the indices which correspond to the intersection of the two
    arrays are returned. The first instance of a value is used if there are
    multiple. Default is False.

    .. versionadded:: 1.15.0

Returns
-------
intersect1d : ndarray
    Sorted 1D array of common and unique elements.
comm1 : ndarray
    The indices of the first occurrences of the common values in `ar1`.
    Only provided if `return_indices

In [77]:
arr2d = np.array([
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])

row_sums = arr2d.sum(axis = 1)
row_sums

array([ 6, 24, 15])

In [75]:
max_row_index = np.argmax(row_sums)
max_row_index

1

In [76]:
arr2d[max_row_index]

array([7, 8, 9])

In [79]:
neg = np.array([1, -2, 3, -4, 5])
neg

array([ 1, -2,  3, -4,  5])

In [81]:
neg[neg < 0]

array([-2, -4])

In [82]:
ar1 = np.array([1,2,3])
ar2 = np.array([2,3,4])

np.setxor1d(ar1, ar2)

array([1, 4])

In [84]:
ar2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
ar2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
rowsum = ar2d.sum(axis = 0)
rowsum

array([12, 15, 18])

In [91]:
ar2d[np.argmin(rowsum)]

array([1, 2, 3])

sinif not sistemi

In [92]:
notlar = np.array(np.random.randint(0, 101, size = 50))
notlar

array([37, 30, 77, 66, 69, 45, 95, 53, 10, 15, 34, 51, 97, 10, 24, 69, 18,
       37, 90, 30, 22,  0, 32,  7, 71, 78, 81, 52, 88, 46, 61,  0, 36, 97,
       19, 69, 38, 45,  7, 15, 44, 57, 96, 83, 70, 34, 98, 10, 12, 14])

In [103]:
ortalama = notlar.mean()
gecenler = []
kalanlar = []
for i in range(notlar.size):
    if notlar[i] >= ortalama:
        gecenler.append(notlar[i])
    else:
        kalanlar.append(notlar[i])

In [104]:
gecenler

[77,
 66,
 69,
 95,
 53,
 51,
 97,
 69,
 90,
 71,
 78,
 81,
 52,
 88,
 61,
 97,
 69,
 57,
 96,
 83,
 70,
 98]

In [105]:
kalanlar

[37,
 30,
 45,
 10,
 15,
 34,
 10,
 24,
 18,
 37,
 30,
 22,
 0,
 32,
 7,
 46,
 0,
 36,
 19,
 38,
 45,
 7,
 15,
 44,
 34,
 10,
 12,
 14]

In [106]:
ortalama = notlar.mean()
ortalama

46.78

In [107]:
notlar.max()

98

Bir array içindeki negatif sayıları sıfır yap.

In [108]:
array1 = np.array([-5, 3, -1, 7])
array1

array([-5,  3, -1,  7])

In [110]:
for i in range(array1.size):
    if array1[i]<0:
        array1[i]=0
    else:
        continue
array1

array([0, 3, 0, 7])

İki array'in ortak olmayan elemanlarını birleştir.

In [112]:
arr1 = [1,2,3]
arr2 = [2,3,4]
common = np.setxor1d(arr1, arr2)
common


array([1, 4])

Bir array'deki tüm elemanların karesini al.

In [114]:
array2 = np.array([2, 3, 4])

for i in range(array2.size):
    array2[i] = array2[i] * array2[i]
    
array2

array([ 4,  9, 16])

5x5 bir random array üret.

In [116]:
rndarr = np.random.randint(0, 100, size = (5, 5))
rndarr

array([[73, 57,  6, 17, 48],
       [30, 34, 11, 87,  6],
       [19, 58, 30, 99,  6],
       [31, 80, 38, 55, 68],
       [ 2, 80, 90, 78, 62]])

Bir array'deki en büyük 3 elemanı bul.

In [133]:
arr = np.array([1, 9, 3, 7, 5, 11, 4, 10])
top3_indices = np.argsort(arr)[-3:]  # En büyük 3'ün indeksini al
top3_values = arr[top3_indices]
top3_values 

array([ 9, 10, 11])

Bir array'in ortalamasının üstünde olan tüm elemanları seç.

In [118]:
nar = np.array([10, 20, 30, 40])
ortustu = []
for i in range(nar.size):
    if nar.mean() < nar[i]:
        ortustu.append(nar[i])
    else:
        continue

ortustu
        

[30, 40]

Verilen bir 2D array'de:

Her satırın toplamını bul

Toplamı en küçük olan satırı yazdır.

In [121]:
arr2d = np.array([[73, 57,  6, 17, 48],
       [30, 34, 11, 87,  6],
       [19, 58, 30, 99,  6],
       [31, 80, 38, 55, 68],
       [ 2, 80, 90, 78, 62]])

rowsum = arr2d.sum(axis = 1)
rowsum

array([201, 168, 212, 272, 312])

In [123]:
arr2d[np.argmin(rowsum)]

array([30, 34, 11, 87,  6])

Bir array'de:

Eğer sayı çiftse 2 ile çarp

Eğer tekse 3 ekle

(ve yeni bir array oluştur)

In [124]:
arrs = np.array(np.random.randint(1, 10, size = 12))
arrs

array([4, 7, 4, 3, 9, 5, 6, 4, 8, 1, 9, 8])

In [125]:
newarrs = []
for i in range(arrs.size):
    if arrs[i] % 2 == 0:
        newarrs.append(arrs[i] * arrs[i])
    else:
        newarrs.append(arrs[i] + 3)

newarrs

[16, 10, 16, 6, 12, 8, 36, 16, 64, 4, 12, 64]

Bir 2D array'i satır satır ters çevir.

In [143]:
ar2d = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

resar2d = ar2d[:, ::-1]

resar2d

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

Bir array'in elemanlarını küçükten büyüğe sırala,
ama orijinal array'i değiştirme.
(yani kopyasını sırala)

In [137]:
ar = np.array(np.random.randint(1, 100, size = 10))
newar = np.sort(ar)

In [138]:
ar

array([76, 22, 76, 12, 12, 56, 53, 40,  1, 11])

In [139]:
newar

array([ 1, 11, 12, 12, 22, 40, 53, 56, 76, 76])